import tkinter as tk
a=tk.Tk()
a.config(bg='#FFEBCD')
logo=tk.PhotoImage(file="-icon-png-image_3232032.png")
a.iconphoto(False,logo)
a.geometry("625x335+100+100")
a.title("Программа")
a.resizable(True,False)
def arr():
   file=open('reg.txt','w')
   file.write("Имя-"+name.get()+'\n')
   file.write("Фамилия-"+surname.get()+'\n')
   file.write("Отчество-"+отчество.get()+'\n')
   file.write("Город-"+город.get()+'\n')
   file.write("Год рождения-"+гр.get()+'\n')
   file.write("Почта-"+почта.get()+'\n')
   file.write("Пароль-"+пароль.get()+'\n')
   file.write("Подтверждение пароля-"+под_пароль.get()+'\n')
   file.close()
   name.delete(0,tk.END)
   surname.delete(0,tk.END)
   отчество.delete(0,tk.END)
   город.delete(0,tk.END)
   гр.delete(0,tk.END)
   почта.delete(0,tk.END)
   пароль.delete(0,tk.END)
   под_пароль.delete(0,tk.END)
   label=tk.Label(a,text="Заявка подана")
   label.grid(row=9,column=1)
  


name=tk.Entry(a)
lab=tk.Label(text='Имя')
surname=tk.Entry(a)
sm=tk.Label(text='Фамилия')
отчество=tk.Entry(a)
отч=tk.Label(text='Отчество')
name.grid(row=0,column=1)
lab.grid(row=0,column=0)
surname.grid(row=1,column=1)
sm.grid(row=1,column=0)
отчество.grid(row=2,column=1)
отч.grid(row=2,column=0)
город=tk.Entry(a)
гд=tk.Label(text='Город')
город.grid(row=3,column=1)
гд.grid(row=3,column=0)
гр=tk.Entry(a)
годр=tk.Label(text='Год рождения')
гр.grid(row=7,column=1)
годр.grid(row=7,column=0)
почта=tk.Entry(a)
почт=tk.Label(text='Почта')
почта.grid(row=4,column=1)
почт.grid(row=4,column=0)
пароль=tk.Entry(a,show='*')
пар=tk.Label(text='Пароль')
пароль.grid(row=5,column=1)
пар.grid(row=5,column=0)
под_пароль=tk.Entry(a,show='*')
под_пар=tk.Label(text='Подтверждение пароля')
под_пароль.grid(row=6,column=1)
под_пар.grid(row=6,column=0)
под_зая=tk.Button(a,text='Подать заявку',command=arr)
под_зая.grid(row=8,column=1)


a.mainloop()
